# Generated by Django 3.1.5 on 2021-02-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_auto_20210207_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='color',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='color_2',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
